version: "3.8"
services:
  db:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8000:27017
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=amcef
    ports:
      - 8001:80
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on:
      - db
      - server
